### ISSUE TITLE
can't run jekyll

### ISSUE THREAD

**Issue by karlp** [lede-project/web#35]
no idea how to make ruby behave.  installed jekyll, installed ruby-dev, ruby-ffi, blah

```
$ bundle exec jekyll serve
Configuration file: /home/karlp/src/lede-docs-web/_config.yml
            Source: /home/karlp/src/lede-docs-web
       Destination: /home/karlp/src/lede-docs-web/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
/home/karlp/.gem/ruby/gems/jekyll-3.1.6/lib/jekyll/filters.rb:2:in `require': cannot load such file -- json (LoadError)
    from /home/karlp/.gem/ruby/gems/jekyll-3.1.6/lib/jekyll/filters.rb:2:in `<top (required)>'
    from /home/karlp/.gem/ruby/gems/jekyll-3.1.6/lib/jekyll/renderer.rb:53:in `run'
    from /home/karlp/.gem/ruby/gems/jekyll-3.1.6/lib/jekyll/site.rb:179:in `block in render'
    from /home/karlp/.gem/ruby/gems/jekyll-3.1.6/lib/jekyll/site.rb:177:in `each'
    from /home/karlp/.gem/ruby/gems/jekyll-3.1.6/lib/jekyll/site.rb:177:in `render'
    from /home/karlp/.gem/ruby/gems/jekyll-3.1.6/lib/jekyll/site.rb:59:in `process'
    from /home/karlp/.gem/ruby/gems/jekyll-3.1.6/lib/jekyll/command.rb:26:in `process_site'
    from /home/karlp/.gem/ruby/gems/jekyll-3.1.6/lib/jekyll/commands/build.rb:60:in `build'
    from /home/karlp/.gem/ruby/gems/jekyll-3.1.6/lib/jekyll/commands/build.rb:33:in `process'
    from /home/karlp/.gem/ruby/gems/jekyll-3.1.6/lib/jekyll/commands/serve.rb:34:in `block (2 levels) in init_with_program'
    from /home/karlp/.gem/ruby/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `call'
    from /home/karlp/.gem/ruby/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
    from /home/karlp/.gem/ruby/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
    from /home/karlp/.gem/ruby/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
    from /home/karlp/.gem/ruby/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
    from /home/karlp/.gem/ruby/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
    from /home/karlp/.gem/ruby/gems/jekyll-3.1.6/bin/jekyll:13:in `<top (required)>'
    from /home/karlp/bin/jekyll:23:in `load'
    from /home/karlp/bin/jekyll:23:in `<main>'
karlp@cuth:~/src/lede-docs-web (mdns-basics)$ jekyll serve
WARN: Unresolved specs during Gem::Specification.reset:
      ffi (>= 0.5.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/usr/share/gems/gems/bundler-1.7.8/lib/bundler/runtime.rb:34:in `block in setup': You have already activated colorator 1.1.0, but your Gemfile requires colorator 0.1. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
    from /usr/share/gems/gems/bundler-1.7.8/lib/bundler/runtime.rb:19:in `setup'
    from /usr/share/gems/gems/bundler-1.7.8/lib/bundler.rb:122:in `setup'
    from /home/karlp/.gem/ruby/gems/jekyll-3.2.1/lib/jekyll/plugin_manager.rb:36:in `require_from_bundler'
    from /home/karlp/.gem/ruby/gems/jekyll-3.2.1/exe/jekyll:9:in `<top (required)>'
    from /home/karlp/bin/jekyll:23:in `load'
    from /home/karlp/bin/jekyll:23:in `<main>'
karlp@cuth:~/src/lede-docs-web (mdns-basics)$ 
```

**Comment by jow-** [comment]
I assume this is fixed now.
